/**
 * Type definitions for Cloudflare Workers environment
 */

// Use the generated Env interface from worker-configuration.d.ts
// This extends the Cloudflare.Env interface generated by wrangler types

export interface SentenceData {
  sentence: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

export interface SentenceResponse {
  sentence: string;
  date: string;
  difficulty: string;
  success: boolean;
}

export interface ScoreSubmissionRequest {
  playerName: string;
  dailyScore: number;
  gameDate: string;
}

export interface ScoreSubmissionResponse {
  success: boolean;
  message?: string;
  playerName?: string;
  dailyScore?: number;
  gameDate?: string;
  cumulativeScore?: number;
  gamesPlayed?: number;
  error?: string;
}

export interface LeaderboardEntry {
  playerName: string;
  cumulativeScore: number;
  gamesPlayed: number;
  lastPlayedDate: string;
}

export interface LeaderboardResponse {
  success: boolean;
  leaderboard?: LeaderboardEntry[];
  totalPlayers?: number;
  lastUpdated?: string;
  error?: string;
}

export interface ErrorResponse {
  error: string;
  code?: string;
  details?: any;
}