// Generated by Wrangler by running `wrangler types`

/// <reference types="@cloudflare/workers-types" />

interface Env {
	SENTENCES_KV: KVNamespace;
	ALLOWED_ORIGINS: "https://yourusername.github.io";
	GAME_DB: D1Database;
}
