name: Deploy Cloudflare Worker

on:
  push:
    branches: [ main ]
    paths: 
      - 'worker/**'
  workflow_dispatch:

env:
  NODE_VERSION: '22'

jobs:
  deploy-worker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: 'worker/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
      working-directory: ./worker
    
    - name: Build TypeScript
      run: npx wrangler types
      working-directory: ./worker
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    
    - name: Validate configuration
      run: node validate-config.js
      working-directory: ./worker
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    
    - name: Deploy to Cloudflare Workers
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        workingDirectory: './worker'
        command: deploy --env production